In [ ]:
# download tensoflow-GPU and CUDA package to use GPU

import tensorflow as tf
tf.__version__

'2.11.0'

In [ ]:
# tf constants
x = tf.constant(10.0)
y = tf.constant(15.0)
z = x+y
print(x+y)
print(x*y)

tf.Tensor(25.0, shape=(), dtype=float32)
tf.Tensor(150.0, shape=(), dtype=float32)


In [ ]:
# tf variables 
x = tf.Variable(initial_value = ([[1,2,3,4],[5,6,7,8]]),dtype="int32",name="x")
print(x)
print(x.shape)
tf.rank(x)

<tf.Variable 'x:0' shape=(2, 4) dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)>
(2, 4)


<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
x = tf.constant(50,shape=[6,2])
print(tf.rank(x))
print(x.shape)
x

tf.Tensor(2, shape=(), dtype=int32)
(6, 2)


<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[50, 50],
       [50, 50],
       [50, 50],
       [50, 50],
       [50, 50],
       [50, 50]], dtype=int32)>

# Tensorflow for Linear Regression

In [ ]:
w = tf.Variable([0.3],tf.float32)
b = tf.Variable([-0.3],tf.float32)

x = tf.Variable([5.0],tf.float32)

y = w*x+b

print(w)
print(b)
print(x)
print(y)

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.3], dtype=float32)>
<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-0.3], dtype=float32)>
<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([5.], dtype=float32)>
tf.Tensor([1.2], shape=(1,), dtype=float32)


In [ ]:
train_x = [3.3, 4.4, 5.5, 6.71, 6.93, 4.168, 9.779, 6.182, 7.59, 2.167,
           7.042, 10.791, 5.313, 7.997, 5.654, 9.27, 3.1]
train_y = [1.7, 2.76, 2.09, 3.19, 1.694, 1.573, 3.366, 2.596, 2.53, 1.221,
           2.827, 3.465, 1.65, 2.904, 2.42, 2.94, 1.3]

num_examples = len(train_x)

#initializing the weights and bais
w = tf.Variable(0.0)
b = tf.Variable(0.0)

learning_rate = 0.01

#like a graph for later execution
for i in range(100):
  with tf.GradientTape() as tape:
    yhat = (train_x * w) + b
    error = yhat - train_y
    loss = tf.reduce_mean(tf.square(error))

  dw,db = tape.gradient(loss, [w,b])

  #update new weights and bias
  w.assign_sub(dw*learning_rate)
  b.assign_sub(db * learning_rate)

  if i%20 == 0:
    print("loss at step",i,"is",loss)

loss at step 0 is tf.Tensor(6.1000323, shape=(), dtype=float32)
loss at step 20 is tf.Tensor(0.21677592, shape=(), dtype=float32)
loss at step 40 is tf.Tensor(0.21094671, shape=(), dtype=float32)
loss at step 60 is tf.Tensor(0.20565753, shape=(), dtype=float32)
loss at step 80 is tf.Tensor(0.20085843, shape=(), dtype=float32)


In [ ]:
# MNIST classification dataset
import tensorflow as tf

In [ ]:
mnist = tf.keras.datasets.mnist

(x_train,y_train),(x_test,y_test) = mnist.load_data()
x_train,x_test = x_train/255.0, x_test/255.0

11490434/11490434 [==============================] - 0s 0us/step


Build the model, choose an optimizer and loss function

In [ ]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [ ]:
# looking at model output format
pred = model(x_train[:1]).numpy()
pred

array([[-0.40073752,  0.22245456, -0.0155752 ,  0.1172137 , -0.0716653 ,
        -0.41292155,  0.49422532,  0.04418721,  0.56148744, -0.75208414]],
      dtype=float32)

In [ ]:
# getting the probabilistic output for each class

tf.nn.softmax(pred).numpy()

array([[0.06361425, 0.11863239, 0.09350359, 0.10678194, 0.08840334,
        0.06284387, 0.15567964, 0.09926193, 0.16651118, 0.04476788]],
      dtype=float32)

In [ ]:
# getting the loss
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1],pred)

<tf.Tensor: shape=(), dtype=float32, numpy=2.7671018>

In [ ]:
# Comipling the model
model.compile(optimizer="adam",
              loss = loss_fn,
              metrics=["accuracy"])

In [ ]:
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 11s 4ms/step - loss: 0.2944 - accuracy: 0.9139
Epoch 2/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1426 - accuracy: 0.9573
Epoch 3/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.1055 - accuracy: 0.9684
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0869 - accuracy: 0.9735
Epoch 5/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0739 - accuracy: 0.9771


In [ ]:
model.fit(x_train,y_train,epochs=20)

Epoch 1/20
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0628 - accuracy: 0.9805
Epoch 2/20
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0590 - accuracy: 0.9811
Epoch 3/20
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0537 - accuracy: 0.9825
Epoch 4/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0494 - accuracy: 0.9836
Epoch 5/20
1875/1875 [==============================] - 7s 3ms/step - loss: 0.0431 - accuracy: 0.9854
Epoch 6/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0424 - accuracy: 0.9858
Epoch 7/20
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0391 - accuracy: 0.9874
Epoch 8/20
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0369 - accuracy: 0.9873
Epoch 9/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0342 - accuracy: 0.9885
Epoch 10/20
1875/1875 [==============================] - 7s 3ms/step - loss: 0.0

In [ ]:
model.evaluate(x_test,y_test,verbose=0)

[0.08757012337446213, 0.9815000295639038]

In [ ]:
#wine dataset
import pandas as pd
import numpy as np

# Read in white wine data 
white = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv", sep=';')

# Read in red wine data 
red = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv", sep=';')


In [ ]:
print(white.info())
print(red.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         4898 non-null   float64
 1   volatile acidity      4898 non-null   float64
 2   citric acid           4898 non-null   float64
 3   residual sugar        4898 non-null   float64
 4   chlorides             4898 non-null   float64
 5   free sulfur dioxide   4898 non-null   float64
 6   total sulfur dioxide  4898 non-null   float64
 7   density               4898 non-null   float64
 8   pH                    4898 non-null   float64
 9   sulphates             4898 non-null   float64
 10  alcohol               4898 non-null   float64
 11  quality               4898 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 459.3 KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column   

In [ ]:
red.isnull().sum().sum()

0

In [ ]:
white.isnull().sum().sum()

0

In [ ]:
red.shape,white.shape

((1599, 12), (4898, 12))

In [ ]:
red['type'] = 1
white['type'] = 0
wines = red.append(white,ignore_index=True)
wines.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  type  
0      9.4        5     1  
1      9.8        5     1  
2      9.8        5     1  
3      9.8        6     1  
4      9.4        5     1

In [ ]:
wines.tail()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
6492            6.2              0.21         0.29             1.6      0.039   
6493            6.6              0.32         0.36             8.0      0.047   
6494            6.5              0.24         0.19             1.2      0.041   
6495            5.5              0.29         0.30             1.1      0.022   
6496            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
6492                 24.0                  92.0  0.99114  3.27       0.50   
6493                 57.0                 168.0  0.99490  3.15       0.46   
6494                 30.0                 111.0  0.99254  2.99       0.46   
6495                 20.0                 110.0  0.98869  3.34       0.38   
6496                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  type  
6492     11.2        6     0  
6493      9.6        5     0  
6494      9.4        6     0  
6495     12.8        7     0  
6496     11.8        6     0

In [ ]:
wines.shape

(6497, 13)

In [ ]:
from sklearn.model_selection import train_test_split

# Specify the data 
x=wines.drop("type",axis=1)

# Specify the target labels and flatten the array
y= np.ravel(wines.type)
#y= wines.type

# Split the data up in train and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler

# Define the scaler 
scaler = StandardScaler().fit(x_train)

# Scale the train set
x_train = scaler.transform(x_train)

# Scale the test set
x_test = scaler.transform(x_test)

In [ ]:
#Building the neural network model
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()

model.add(Dense(12,activation="relu",input_shape=(12,)))
model.add(Dense(8,activation="relu"))
model.add(Dense(1,activation="relu"))

In [ ]:
model.compile(loss="binary_crossentropy",
              optimizer='adam',
              metrics=['accuracy'])
model.fit(x_train,y_train,epochs=20,batch_size=1,verbose=1)

Epoch 1/20
4547/4547 [==============================] - 11s 2ms/step - loss: 0.0751 - accuracy: 0.9824
Epoch 2/20
4547/4547 [==============================] - 13s 3ms/step - loss: 0.0416 - accuracy: 0.9952
Epoch 3/20
4547/4547 [==============================] - 19s 4ms/step - loss: 0.0355 - accuracy: 0.9963
Epoch 4/20
4547/4547 [==============================] - 12s 3ms/step - loss: 0.0480 - accuracy: 0.9954
Epoch 5/20
4547/4547 [==============================] - 12s 3ms/step - loss: 0.0397 - accuracy: 0.9967
Epoch 6/20
4547/4547 [==============================] - 18s 4ms/step - loss: 0.0354 - accuracy: 0.9967
Epoch 7/20
4547/4547 [==============================] - 19s 4ms/step - loss: 0.0343 - accuracy: 0.9974
Epoch 8/20
4547/4547 [==============================] - 14s 3ms/step - loss: 0.0333 - accuracy: 0.9971
Epoch 9/20
4547/4547 [==============================] - 14s 3ms/step - loss: 0.0296 - accuracy: 0.9974
Epoch 10/20
4547/4547 [==============================] - 16s 4ms/step - l

In [ ]:
y_pred = np.round(model.predict(x_test))
y_pred[:10]

61/61 [==============================] - 1s 2ms/step


array([[0.],
       [2.],
       [0.],
       [0.],
       [0.],
       [4.],
       [0.],
       [0.],
       [2.],
       [0.]], dtype=float32)

In [ ]:
print("Test metrics : ",model.evaluate(x_test,y_test,verbose=0))
print("Train metrics : ",model.evaluate(x_train,y_train,verbose=0))

Test metrics :  [0.08867396414279938, 0.9933333396911621]
Train metrics :  [0.027453208342194557, 0.9980206489562988]
